name: RUN PIPELINE ON SCHEDULED TIME   
on:
  schedule:
    - cron: '13 12 * * *'
  push:
    branches:
      - main    
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print date and time
        run: |
          echo "Current date: $(date)"
